### ISSUE TITLE
always getting this error when payment

### ISSUE THREAD

**Issue by kjpmantos** [stripe/stripe-java#1001]
{"error":{"code":null,"message":"Invalid null ID found for url path formatting. This can be because your string ID argument to the API method is null, or the ID field in your stripe object instance is null. Please contact support@stripe.com on the latter case. "}}

i already tried the latest stripe-java version 18.13.1 and got this error. so i revert to my original used version 17.6.0. on the local machine it looks fine. but when in staging/live we always get this error.

**Comment by remi-stripe** [comment]
@kjpmantos Since you closed the issue already I'm assuming you found the problem but just in case: this error usually happens when one of the ids you pass as parameters, such as an invoice id when retrieving an invoice or an account id when creating a person, is null or the empty string. Checking the parameters you pass to that method should help you narrow things down.

**Comment by kjpmantos** [comment]
Thanks. i got the solution already. your right. thats the reason of the
error. thanks by the way.
