### ISSUE TITLE
StripeCollection should implement java.util.Iterable

### ISSUE THREAD

**Issue by michaelklishin** [stripe/stripe-java#101]
Currently `StripeCollection` subclasses are somewhat inconvenient to iterate over, even though semantically they represent a lazy collection (or result set cursor).

Have you considered making `StripeCollection` implement java.util.Iterable? Would a pull request
that makes the change have a chance at getting merged?

**Comment by craigsoules** [comment]
Since it seems you guys are not in favor of supporting lazy iteration, I'll instead propose for the collections that implement calls like all() have those calls defined through an interface that they implement.  Then we could at least write a template-based wrapper that could do the lazy iteration even if you guys don't want to support it.

Right now I've got pagination double-looping all over the place in our code, which makes it very unreadable and hard to maintain.

Thanks!

**Comment by hardtoe** [comment]
Pull request #125 which implemented StripeCollection iteration without lazy-loading was rejected.  According to that discussion a lazy-loading implementation is favored instead.  

Recently submitted pull request #208 implements iterable StripeCollections and StripeCollectionAPIResources.  A version of either #125 or #208 should be accepted to close this issue.

**Comment by kyleconroy** [comment]
Just wanted to update everyone on the status of pagination. We have a PR open to (https://github.com/stripe/stripe-java/pull/228) that we're hoping to merge in this week..

**Comment by brandur** [comment]
A release is still pending, but #228 is now merged to master. Closing this issue out. Sorry about the fairly extreme time to resolve!
