### ISSUE TITLE
Please annotate deprecated methods / fields

### ISSUE THREAD

**Issue by totof3110** [stripe/stripe-java#1011]
I noticed that deprecated methods / field in the Java SDK look like:
```
  /**
   * [DEPRECATED] The currency of the <a
   * href="https://stripe.com/docs/api#issuing_authorization_object-held_amount">held amount</a>.
   * This will always be the card currency.
   */
  @SerializedName("held_currency")
  String heldCurrency;
```
This `[DEPRECATED]` comment is not standard and does not trigger compiler warnings, which makes it very hard to detect their usage and prepare for their removal.

Could you annotate them with the standard `@Deprecated` annotation and / or the `/** @deprecated */` JavaDoc?

**Comment by remi-stripe** [comment]
@totof3110 Thanks for reaching out! We definitely know the current approach isn't the best and it's something we would like to improve in the future.

At the moment we use this temporarily to just ensure new developers don't use those fields by mistake, which they would hopefully notice with the javadoc in their IDE. It's also reflected in the API reference itself.

Our plan though is to encode this in the openapi spec itself so that we can easily detect deprecated parameters, properties or API methods in the spec and have all our client libraries automatically reflect this information the right way in each language.

The changes mentioned here were also a bit particular. We usually don't make breaking changes like this to public APIs without a new API version. Here though, the Issuing APIs were in beta with a limited number of accounts until this week and we took the opportunity to clean a lot of the API before we released it publicly for everyone.

I hope this helps provide some more context around this. I'm going to close this issue and tag is as future but know that it is on our roadmap and we're tracking those kinds of improvements internally too!
