### ISSUE TITLE
Min version to use Checkout

### ISSUE THREAD

**Issue by fernandoarau90** [stripe/stripe-java#1018]
Hi, i need to know what is the minimum version to use Checkouts. Thanks!

**Comment by remi-stripe** [comment]
@fernandoarau90 While support for Checkout `Session` was added in [9.3.0](https://github.com/stripe/stripe-java/blob/master/CHANGELOG.md#930---2019-04-16) we shipped multiple improvements over the past year such as new properties and parameters. I would recommend always using the latest version of stripe-java when you integrate a new product to ensure that you don't lose out on core features. 

If you can't upgrade to the latest, I'd recommend at least [17.13.0](https://github.com/stripe/stripe-java/blob/master/CHANGELOG.md#17130---2020-02-24) since it added the ability to list `Session` via the API.

**Comment by fernandoarau90** [comment]
@remi-stripe thanks
