### ISSUE TITLE
"Invalid array" when I'm trying to get an upcoming invoice with updated quantity 

### ISSUE THREAD

**Issue by aldo-israel** [stripe/stripe-java#1037]
Stripe-java ver. 19.16.0
JDK ver. 1.8

I'm trying with the Stripe API to get a next invoice from a customer, with a quantity parameter.

Here is my code:

`Map<String, Object> invoiceParams = new HashMap<>();
invoiceParams.put("customer", cus_12345678);
invoiceParams.put("subscription", "sub_12345678");
invoiceParams.put("subscription_prorate", true);
			
Map<String, Object> subscriptionItemsParams = new HashMap<>();
subscriptionItemsParams.put("id", si_12345678);
subscriptionItemsParams.put("quantity", 10);
			
invoiceParams.put("subscription_items", subscriptionItemsParams);return Invoice.upcoming(invoiceParams);`

But I'm getting the following error:

`{
  "error": {
    "message": "Invalid array",
    "param": "subscription_items",
    "type": "invalid_request_error"
  }
}`

Thanks in advance.

**Comment by remi-stripe** [comment]
@aldo-israel Github issues should be limited to bugs with the library itself or feature requests. Since this question is a question about our API itself I'm going to close. If you have any follow up questions please make sure to contact our support team instead: https://support.stripe.com/contact


To make this easier though, the issue is that `items` is an array of arrays. So you need this instead:

```
Map<String, Object> invoiceParams = new HashMap<>();
invoiceParams.put("customer", cus_12345678);
invoiceParams.put("subscription", "sub_12345678");
invoiceParams.put("subscription_prorate", true);

Map<String, Object> subscriptionItemsParams = new HashMap<>();

Map<String, Object> item1Params = new HashMap<>();
item1Params.put("id", si_12345678);
item1Params.put("quantity", 10);

List<Object> items = new ArrayList<>();
items.add(item1Params);

invoiceParams.put("subscription_items", items);
return Invoice.upcoming(invoiceParams);
```
