### ISSUE TITLE
Retrocompatibility issue

### ISSUE THREAD

**Issue by Kenji94** [stripe/stripe-java#1053]
Hello,

Following "19.27.0 - 2020-06-24 #1052 Add support for invoice.paid event",
I got an issue on prod.
I'm on the version: com.stripe:stripe-java:18.16.0.

My problem is that I'm using EnabledEvent (com.stripe.param.WebhookEndpointCreateParams.EnabledEvent) to identify the event type.

```
EnabledEvent eventType = StripeUtils.getEventType(event.getType());

  public static WebhookEndpointCreateParams.EnabledEvent getEventType(String type) {
    for (WebhookEndpointCreateParams.EnabledEvent enabledEvent : WebhookEndpointCreateParams.EnabledEvent.values()) {
      if (enabledEvent.getValue().equals(type)) {
        return enabledEvent;
      }
    }
    throw new IllegalArgumentException("EnabledEvent not found for " + type);
  }
```

To fix this bug, it is easy: update to last version.
But what is the best way to avoid properly next issues ?

Thank you,
Thibault

**Comment by remi-stripe** [comment]
@Kenji94 Thanks for reaching out! Today, stripe-java does not support enum values for _properties_, only for _parameters_. I would recommend avoiding using the enum inside the params classes to do any custom matching on properties and resources to avoid this situation.

The cleanest would be to use the raw string value instead of looking for an enum for the event type when you receive the data. So instead of trying to do `WebhookEndpointCreateParams.EnabledEvent.CHARGE__SUCCEEDED`, I'd recommend using `"charge.succeeded"` instead in your code.

We hope to add enum support on resources in the future but we have deferred for now. library. Adding new enum values is not considered a breaking change in the API on Stripe's end. But for cases like this it would cause issue on older versions of the library which is problematic.

I hope this clarifies the situation!
