### ISSUE TITLE
Need help with charge radar rules in the stripe java library

### ISSUE THREAD

**Issue by ta-shi** [stripe/stripe-java#1101]
https://stripe.com/docs/radar/rules/skip-rules

```
ChargeCreateParams params =
                ChargeCreateParams.builder()
                        .setAmount(amount)
                        .setCustomer(customerId)
                        .setCurrency("usd")
                        .setTransferGroup(orderId)
                        .putExtraParam("radar_options[skip_rules]", "all")
                        .setDescription("Example charge + " + orderId)
                        .build();

        RequestOptions chargeRequestOption =
                RequestOptions.builder()
                        .setApiKey(requestOptions.getApiKey())
                        .setIdempotencyKey("charge-"+orderId)
                        .build();

        Charge charge = Charge.create(params, chargeRequestOption);
```

Received 

`Caused by: com.stripe.exception.InvalidRequestException: Received unknown parameter: radar_options[skip_rules]; code: parameter_unknown; request-id: req_mE33TBoIFFRm41`

**Comment by remi-stripe** [comment]
@ta-shi That error means the account associated with that request does not have access to that feature. You need to make sure you use the API keys associated with the account that has been gated into the feature. I would recommend contacting our support team instead since you're discussing a private/secret feature that is not public for everyone.

Please reach out to them here: https://support.stripe.com/contact

**Comment by ta-shi** [comment]
Thank you @remi-stripe  for clearing that up. It worked with our prod account (test mode) where Radar feature is already enabled. 

Very minor : 
Updated suggested code 
`.putExtraParam("radar_options[skip_rules]", "all")`
to
`.putExtraParam("radar_options[skip_rules]", Collections.singletonList("all"))`
Since "skip_rules" accepts string array.

🙌

**Comment by remi-stripe** [comment]
Ah yes I forgot it was an array thanks for circling back!
