### ISSUE TITLE
Why was taxPercent removed from com.stripe.model.Subscription ?

### ISSUE THREAD

**Issue by sflahave** [stripe/stripe-java#1121]
Upgrading from `19.42.0` to `20.14.0` fails because `com.stripe.model.Subscription.taxPercent` was removed. I can't find any documentation explaining why it was removed or what we should do instead.

**Comment by remi-stripe** [comment]
@sflahave `tax_percrent` was removed from the API in the latest API version which is documented [here](https://stripe.com/docs/upgrades#2020-08-27). Since stripe-java is always pinned to the latest API version, it introduces those breaking changes each time.
Instead of `tax_percent` you should use the TaxRate API as documented here: https://stripe.com/docs/billing/taxes/tax-rates
