### ISSUE TITLE
How to get the account ID from a payout?

### ISSUE THREAD

**Issue by pkatul** [stripe/stripe-java#1145]
How to know if a payout was for platform account or connected account?
There should be a way to find out the connected account ID if the payout was for connected account.

**Comment by remi-stripe** [comment]
@pkatul To retrieve or interact with a Payout resource, your code should already know which account this is on, otherwise you wouldn't be able to use it.

My guess here is that you are not talking about a Payout itself and instead are talking about your webhook handler where you get a `payout.created` event for example. If that is correct, the `Event` object has the `account` property documented [here](https://stripe.com/docs/api/events/object#event_object-account) which is set to the id of the connected account if the event comes from a connected account or would be null if it's for your own account. This should help you detect the correct account id with code and is also documented in more details here: https://stripe.com/docs/connect/webhooks

I'm going to close out the issue as Github issues should be limited to bugs with the library and this was more an integration question but if you have any follow up questions, don't hesitate to reach out to our support team: https://support.stripe.com/contact
