### ISSUE TITLE
"No signatures found with expected scheme" issue due to blanks in "Stripe-Signature" recieved header

### ISSUE THREAD

**Issue by anthony-o** [stripe/stripe-java#1150]
I have set up a [Stripe webhook](https://stripe.com/docs/api/webhook_endpoints?lang=java) and on `checkout.session.completed` it is called with the following [`Stripe-Signature` ](https://stripe.com/docs/webhooks/signatures#verify-official-libraries) value: `t=1605192247, v1=7fe7386ae9c6aeea233c06aa36dc2591a4bdac21cd1ec9b9888929965d51b19e, v0=8426831f8960402ab22e92a827bfda52e519e196e3a8657e106459b81de1cf1f` (note the `" "` blank spaces).

And when trying to verify the `Event` object received by this webhook calling `com.stripe.net.Webhook#constructEvent(java.lang.String, java.lang.String, java.lang.String)` (latest `20.26.0` version, but also with `19.27.0` version) API, here is the error I obtain:
```
com.stripe.exception.SignatureVerificationException: No signatures found with expected scheme

	at com.stripe.net.Webhook$Signature.verifyHeader(Webhook.java:79)
	at com.stripe.net.Webhook.constructEvent(Webhook.java:50)
	at com.stripe.net.Webhook.constructEvent(Webhook.java:30)
```

This is due to `com.stripe.net.Webhook.Signature#getSignatures` which assumes that there is no spaces between `scheme`.

Bug would be fixed by using `sigHeader.split(", ?", -1)` instead of `sigHeader.split(",", -1)` I think.

**Comment by remi-stripe** [comment]
@anthony-o Thanks for raising the issue and providing some context and an approach to fix it I really appreciate it!

On our end, when we send the signature for an Event, we do not send a space after the comma, I just confirmed this locally to be safe. That's why our code splits on the comma and does not attempt to remove spaces first.

If you see a space on your end, it likely indicates that something is tampering with the header or the data we sent. Are you able to add some logging really early in your stack to dump the exact raw headers we send you before your code or framework touches the data to confirm?

**Comment by anthony-o** [comment]
Thank you, with your comment I dumped my Spring requests using https://www.baeldung.com/spring-http-logging#1-configure-spring-boot-application and you're right, my front API was receiving `t=1605192247,v1=7fe7386ae9c6aeea233c06aa36dc2591a4bdac21cd1ec9b9888929965d51b19e,v0=8426831f8960402ab22e92a827bfda52e519e196e3a8657e106459b81de1cf1f` without space and passing to a backend API which was receiving the spaces...

My front controller which uses a `@FeignClient` to call a backend API:
```java
    private final WebHookRestClient webHookRestClient;

    @PostMapping("/payment-confirmation")
    @Operation(description = "Stripe payment-confirmation WebHook")
    public void stripePaymentConfirmation(@RequestBody String stripeJsonEvent, @RequestHeader("Stripe-Signature") String stripeSignature) throws Exception {
            webHookRestClient.stripePaymentConfirmation(new StripePaymentConfirmationVM().stripeJsonEvent(stripeJsonEvent).stripeSignature(stripeSignature));
    }
```
```java
@FeignClient(name = "web-hook-client", url = "${properties.backend-api.base-url}")
public interface WebHookRestClient extends IWebHookController {
}
```
```java
public interface IWebHookController {
    @PostMapping("/api/web-hooks/payment-confirmation")
    void stripePaymentConfirmation(@RequestBody String stripeJsonEvent, @RequestHeader("Stripe-Signature") String stripeSignature) throws Exception;

}
```
And the backend Controller which implements `IWebHookController` is curiously receiving the spaces... this is perhaps a Feign bug but I'm not able to track it.

I will pass both arguments to the backend API using a DTO instead of `@RequestBody` & `@RequestHeader` this should do the trick, thanks anyway.

**Comment by remi-stripe** [comment]
Thanks for circling back and I'm glad we were able to resolve this!

We could tweak the signature extraction method based on what you recommended but our experience with this is that when a framework tampers with the HTTP headers, it also tends to tamper with the raw body. This usually causes the verification to fail because it uses a different payload from what we sent. It's definitely a thorny issue to solve and one of the most common point of confusion with webhook signatures verification today.
