### ISSUE TITLE
Retrieving the PaymentIntent sometimes fails on WebHook

### ISSUE THREAD

**Issue by KammererTob** [stripe/stripe-java#1160]
When a payment is successful we get notified via Webhook (in "payment_intent.succeeded") and do some post purchase steps, including generating an invoice. 
After that we also want to associate our invoice id with the purchase at stripe to be able to identify them in an export. For that we use the "description" field inside the PaymentIntent object. We update it like this:

```
PaymentIntent paymentIntent = PaymentIntent.retrieve(purchase.getStripeId());

PaymentIntentUpdateParams.Builder paramsBuilder = PaymentIntentUpdateParams
    .builder()
    .setDescription(description);
return paymentIntent.update(paramsBuilder.build());
```

In some rare cases this seems to be unable to retrieve the PaymentIntent and throws this:

> No such payment_intent: 'pi_1HXXXXXXXXXXX'; code: resource_missing; request-id: req_vVGXXXXXXXXX

I can see that the mentioned PaymentIntent ID indeed exists in Stripe and also that the request to create the PaymentIntent was successful a few minutes before this error was logged. Is this a bug? How can we make sure that this does its job?

Java 8
Stripe Java:  19.8.0

**Comment by remi-stripe** [comment]
@KammererTob This looks more like a question about the API itself than a bug in the stripe-java library so I might have to send you to our support team to debug this instead. Before we do that though would you be able to share an exact request id (req_123) so that I can have a look?

**Comment by KammererTob** [comment]
Sure. Here is the request id: req_vVGBrSpC7MCEn1

**Comment by remi-stripe** [comment]
You seem to be mixing up the accounts or your API keys. The request you shared was made on one Stripe account but the PaymentIntent it you are trying to retrieve was created in another/separate Stripe account. My guess is that you have separate accounts that send the events to the same webhook handlers and you are mixing up your API keys.

Since this isn't a bug with stripe-java itself I'm going to close this out. Double checking your API keys or adding a clear log should help you debug this. Otherwise, don't hesitate to contact our support team: https://support.stripe.com/contact

**Comment by KammererTob** [comment]
Ah damn...Thank you. I found the issue!
