### ISSUE TITLE
FileCreateParams.setFile does not accept an input stream

### ISSUE THREAD

**Issue by aspecker** [stripe/stripe-java#1170]
In my use case, I  have to save an input stream generated from the client side request file payload to a temporary file in order to then upload that file to Stripe. The file is then immediately deleted.

I'd like to avoid this performance overhead and pass an input stream to the setFile method. Is this possible?

**Comment by remi-stripe** [comment]
@aspecker The `setFile()` does support `FileInputStream ` as a parameter per [this code](https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/param/FileCreateParams.java#L106). Are you seeing otherwise?

**Comment by remi-stripe** [comment]
Ah it's possible you meant using an `InputStream` directly instead of a `FileInputStream` to not require having to save the file to disk first. Going to tag as future but it's something we should be able to support as the library itself does support it since https://github.com/stripe/stripe-java/pull/935

**Comment by aspecker** [comment]
Thanks for your response Remi, it is great to hear it sounds feasible to support. Appreciate you tagging it for future considering.
