### ISSUE TITLE
Please, add lost parameters to SetupIntent class for AliPay

### ISSUE THREAD

**Issue by altro3** [stripe/stripe-java#1216]
From guide (markes lost parameters from example): ![изображение](https://user-images.githubusercontent.com/48474279/120803554-de807600-c56d-11eb-827e-5c5955f270c8.png)

From API docs:

![изображение](https://user-images.githubusercontent.com/48474279/120803861-31f2c400-c56e-11eb-977b-fac53281df39.png)

From Java sources:

![изображение](https://user-images.githubusercontent.com/48474279/120803949-4d5dcf00-c56e-11eb-85b2-7d3a0741ac89.png)

As you can see in the API docs and guide you have written about the following attribute:
```
payment_method_options.alipay optional dictionary preview feature

If this is a alipay PaymentMethod, this sub-hash contains details about the Alipay payment method options.

payment_method_options.alipay.currency required
```

But, as you can see, this attribute is missing in the Java library .

The second parameter (`payment_method_data`) is missing from the documentation at all. Is this an error in the example and is not required? Or is it an error in the API documentation?

**Comment by remi-stripe** [comment]
@altro3 The feature you're using is around recurring Alipay payments. This feature is in private beta and is not publicly documented, that's why you have the `Preview` tag in the API reference. For now, the best solution is to use `putExtraParam()` in Java to send the parameter directly.

```
SetupIntentCreateParams params =
  SetupIntentCreateParams.builder()
    .addPaymentMethodType("alipay")
    .setCustomer("{{CUSTOMER_ID}}")
    .setConfirm(true)
    .setUsage(SetupIntentCreateParams.Usage.OFF_SESSION)
    // Other normal params
    // Add undocumented/secret parameters
    .putExtraParam("payment_method_data[type]", "alipay")
    .putExtraParam("payment_method_options[alipay][currency]", "cny")
    .build();
```

Since this is more an integration question, I'm going to close this out and recommend that you chat with our support team for follow up questions but hopefully you're unblocked: https://support.stripe.com/contact/email
