### ISSUE TITLE
Feature request: Expose ARN field in Refund object

### ISSUE THREAD

**Issue by ngocng1310** [stripe/stripe-java#1245]
Version of stripe-java: 20.66.0

**Context**: In the docs for tracing a refund (https://stripe.com/docs/refunds#tracing-refunds), it mentions that the Acquirer Reference Number is available after some time on the Stripe dashboard.

**Problem**: Can't find the ARN in the Stripe Java SDK Refund model object (version 20.66.0).
The workaround suggested by Nickn from Stripe team is:
`final Refund refund = Refund.retrieve("re_123");
Gson gson = refund.getRawJsonObject() //then dig into the gson to grab the value`

**Until when the ARN is available in Refund object that we don't have to find it through jsonObject?**

**Comment by remi-stripe** [comment]
@ngocng1310 thanks for reaching out! Since the ARN information is not in our public API it is not in stripe-java (or stripe-dotnet/stripe-go). The library is strongly typed and if we added beta features to it early we might end up with breaking changes as we want to release the feature with a different name or shape for example. Using the `getRawJsonObject()` is the best approach in this case and why we added this to the library. When we ship this feature publicly, it will then be added to stripe-java as the library is automatically generated from our openapi spec.

Since this is more a question about the API itself an not stripe-java I'm going to close this out and you can keep discussing this with Nick on your end!
