### ISSUE TITLE
Portal session

### ISSUE THREAD

**Issue by atigm** [stripe/stripe-java#1282]
I'm using the latest version of Stripe  (20.87.0)
I followed this article https://stripe.com/docs/billing/subscriptions/integrating-customer-portal
Then I'm adding some products and prices to default portal.
```
Stripe.apiKey = ...;
SessionCreateParams params = SessionCreateParams.builder()
                .setCustomer(customerId)
                .setSuccessUrl(successUrl)
                .setCancelUrl(cancelUrl)
                .build();
```

1st problem : There is no more "returnUrl", instead I used "successUrl" and "cancelUrl"

2nd problem : I can't create session, I have this error : **com.stripe.exception.InvalidRequestException You must pass either `subscription_data` or `line_items` or `mode`** but for the portal session we don't need these attributes. 

Thank you

**Comment by remi-stripe** [comment]
@atigm `return_url` still exists on the Customer Portal Session as documented [here](https://stripe.com/docs/api/customer_portal/sessions/create). The error you have is because you are using the Checkout Session types/methods instead of the BillingPortal ones. Make sure you include the correct types and you should be unblocked.

I'm going to close this out as there's no bug with the library/code here and it's an integration question. If you have follow up questions, please contact our support team instead: https://support.stripe.com/contact

**Comment by atigm** [comment]
You are right
Thank you @remi-stripe
