### ISSUE TITLE
Portal session : CROSS origin

### ISSUE THREAD

**Issue by atigm** [stripe/stripe-java#1283]
I'm using the latest version of Stripe (20.87.0)
I followed this article https://stripe.com/docs/billing/subscriptions/integrating-customer-portal
I'm using Spring boot :
```
Session session = paymentService.getPortalSession(url);
        response.sendRedirect(session.getUrl());
```
The session url returned is : **https://billing.stripe.com/session/test_ABC....**

I have this error : 
Chrome : CORS Error 
Firefox : CORS Missing Allow Origin (OPTIONS)

I have the same error in dev (http://localhost) and in integration server (https://mydomain.com)

Thank you

**Comment by remi-stripe** [comment]
@atigm Github issues should be limited to bugs with the library itself. This is an integration question and should be asked to our support team instead: https://support.stripe.com/contact

To unblock you though this error usually happens when you redirect server-side but your client-side code is making an AJAX/fetch request where you can't redirect. You need to either switch to sending back the URL from your server and redirecting client-side, or submit the whole form/page instead of a fetch client-side.
