### ISSUE TITLE
Please add "wallets" field to com.stripe.model.issuing.Card

### ISSUE THREAD

**Issue by totof3110** [stripe/stripe-java#1287]
In JSON there is a `wallets` field populated on the issuing card object, but it is currently not mapped to the Java class. Would it be possible to add it?
```json
    "wallets": {
      "apple_pay": {
        "eligible": true,
        "ineligible_reason": null
      },
      "google_pay": {
        "eligible": true,
        "ineligible_reason": null
      },
      "primary_account_identifier": null
    }
```

**Comment by remi-stripe** [comment]
@totof3110 This feature is not public today which is why it's not in client libraries. We're working on releasing this publicly and once that happens all client libraries will have this included automatically.

I'm going to close this out as you must be in a beta and they should have mentioned/explained this but we don't discuss betas publicly!

**Comment by totof3110** [comment]
@remi-stripe : sorry I didn't know! I've removed the description (since I can't delete the issue).

**Comment by richardm-stripe** [comment]
Hello @totof3110, by complete coincidence, we just publicly released the feature you were asking about today in https://github.com/stripe/stripe-java/releases/tag/v20.90.0

**Comment by totof3110** [comment]
Perfect timing!! Thanks @richardm-stripe ! :laughing:
