### ISSUE TITLE
Add paper_check to the available PaymentMethodTypes

### ISSUE THREAD

**Issue by camerondavison** [stripe/stripe-java#1436]
### Is your feature request related to a problem? Please describe.

Trying to create an invoice with payment method type "paper_check"

https://stripe.com/docs/api/invoices/create?lang=java
<img width="696" alt="Screen Shot 2022-09-09 at 11 56 00 AM" src="https://user-images.githubusercontent.com/165381/189401979-55503097-4668-471f-b7fe-6faa8d004719.png">
<img width="722" alt="Screen Shot 2022-09-09 at 11 56 10 AM" src="https://user-images.githubusercontent.com/165381/189401981-7f31aaed-4e1c-4a6b-b3a9-ab84c72d0efa.png">

### Describe the solution you'd like

Add "paper_check" to https://github.com/stripe/stripe-java/blob/054c8d22dde5f201c8fd876170b02e4cf47071c9/src/main/java/com/stripe/param/InvoiceCreateParams.java#L2648-L2722

**Comment by remi-stripe** [comment]
@camerondavison The Paper Checks feature is in beta and not publicly available to most integrations. It's also built on our legacy and mostly deprecated Sources API and not directly compatible with the PaymentMethod and PaymentIntent API. While it can work, it's not something we want to encourage or support in our public libraries for now which is why this is not documented or in the types.

I'm going to close this out as it's not a change we'll do for now. If and when the Paper Checks feature is ported official to the PaymentMethods API, all our client libraries will support it directly!

**Comment by camerondavison** [comment]
Oh dang. Okay. So what do I do in the mean time?

**Comment by remi-stripe** [comment]
If you have access to the beta, you should be able to use it directly even in Java, you will just have some limitations but you can use https://github.com/stripe/stripe-java#how-to-use-undocumented-parameters-and-properties through stripe-java to pass undocumented parameters/features

I'd recommend working with our support team for help if you need more specific advice, sharing your exact code and what is blocking you and they can help you further: https://support.stripe.com/contact
