### ISSUE TITLE
Can't convert to object in webhooks

### ISSUE THREAD

**Issue by wawahuy** [stripe/stripe-java#1519]
### Describe the bug

A few days ago it was working fine, but since March 28, 2023, it has stopped working.

### To Reproduce

1. purchased
2. stripe call api webhooks
3. all request not working

### Expected behavior

Can be converted to object

### Code snippets

```Java
Event event = Event.GSON.fromJson(json, Event.class);
EventDataObjectDeserializer dataObjectDeserializer = event.getDataObjectDeserializer();
if (dataObjectDeserializer.getObject().isPresent()) {
  // not execute
  // code here
}
```

### OS

Windows 11

### Java version

Java 8

### stripe-java version

v21.15.0

### API version

2022-08-01

**Comment by richardm-stripe** [comment]
Hello @wawahuy, thank you for reporting.

You should contact Stripe support (https://support.stripe.com/contact) and report your issue there. Since this started spontaneously and not as a result of an SDK upgrade, it is most likely *not* an issue with the `stripe-java` library that we can debug via Github issue, and is more likely an issue with Stripe itself, or with your integration. So I am closing the ticket.

I recommend that you log the contents of the `json` variable and include that in your report.
