### ISSUE TITLE
Coupon doesn't get correctly applied when creating customer with subscription

### ISSUE THREAD

**Issue by maxkremer** [stripe/stripe-java#159]
According to the docs you can create a customer, place them on a subscription and apply a coupon in one call like so:

```
Map<String, Object> customerParams = new HashMap<String, Object>();
customerParams.put("description", customerDescription);
customerParams.put("source", stripeToken);
customerParams.put("plan", planCode);
customerParams.put("coupon", couponCode);
Customer stripeCustomer = Customer.create(customerParams);
```

However this will apply the coupon to the first charge but does not associate the coupon with the subscription to the plan.

Steps to reproduce:
- Create a plan
- Create a coupon
- Create a customer on a subscription to the plan with coupon applied as per the code snippet above
- The coupon get applied to the first charge but does not get associated with subscription.

**Comment by jimdanz** [comment]
That flow creates a customer and a *customer-wide* discount.   So the coupon is applied at the customer-level, rather than the subscription level.

The distinction is when a discount is customer-wide, it will apply to charges made on *any* subscription that the customer has, now or ever (until the discount expires).

On the other hand, when a discount is applied to a particular subscription, it applies only to charges made on that subscription.

If you would like to attach a coupon to a particular subscription, you can take an existing customer and use the subscription create call:
https://stripe.com/docs/api/java#create_subscription

**Comment by jimdanz** [comment]
@maxkremer one more thing that I just remembered: when a coupon has `duration=once`, it gets *used* for the first charge, but then will never actually show up in the customer (or subscription) response.  Essentially it gets used for one invoice but then immediately has been exhausted, so it's already gone off the customer or subscription.

Anyway the way to check if that's what's happening for you is to look at the value of `stripeCustomer.getDiscount()` after your example.

**Comment by maxkremer** [comment]
@jimdanz thanks. But if that's the case (the customer-wide discount being applied to all subscriptions) then the subscription should "inherit" the customer wide discount somehow. At the very least it would be great if the above behaviour was documented.
