### ISSUE TITLE
Thread safety of Stripe API calls

### ISSUE THREAD

**Issue by dtsitses** [stripe/stripe-java#1641]
### Describe the bug

I was asking Stripe support if API calls are thread-safe, and they recommended to open a ticket here to get an answer from the developers.

More specifically, it appears that setting the API key in `RequestOptions` and then passing that to an API call (e.g., `Customer.retrieve()`), overwrites the global API key set with `Stripe.apiKey = "..."`

That led me to suspect that API calls may not execute atomically in a thread-safe manner. 

### To Reproduce

If multiple threads call the method below simultaneously but with different `apiKey` arguments, will the correct result be returned every time?

```
public Customer retrieveCustomer(String apiKey) {
    RequestOptions requestOptions = RequestOptions.builder().setApiKey(apiKey).build();
    return Customer.retrieve( "cu_xxxxxxxx", requestOptions);
}
```

### Expected behavior

Passing an API key explicitly in an API call is thread-safe and does not overwrite the global key set by `Stripe.apiKey = ".."`

### OS

OS X 10.15.7

### Java version

1.8.0_281

### stripe-java version

17.0.0

### API version

2022-11-15

**Comment by remi-stripe** [comment]
@dtsitses First, I'm sorry the support team sent you here for help. They have access to engineers internally and should have escalated your request for 1:1 help over email instead.

This feature has been a frequent ask over the years and we have just released a new version (v23.*) which introduces a client/service infrastructure to the library which solves this problem (and many more). It's documented in details in [this wiki](https://github.com/stripe/stripe-java/wiki/Migration-guide-for-v23#stripeclient) and I would highly recommend migrating in this case to ensure thread safety and avoid having to keep "state" by retrieving a resource before you can update or delete it for example.

My understanding (and tests) though confirm that as long as you use `requestOptions` then we will use the API key in that `requestOptions` variable not the global one. For example if you set a fake key globally and create a Customer with a `requestOptions` variable, then the next call without it will fail since the global API key is incorrect.

**Comment by dtsitses** [comment]
@remi-stripe fantastic response, many thanks.
