### ISSUE TITLE
Add network_details to dispute

### ISSUE THREAD

**Issue by zack-harrison** [stripe/stripe-java#1858]
### Is your feature request related to a problem? Please describe.

network_details field is missing. Needed to determine whether a dispute was from RDR (and therefore not a dispute under Visa card brand rules)

### Describe alternatives you've considered

I tried using dispute.getRawJsonObject(), but returns null

**Comment by remi-stripe** [comment]
Hey @zack-harrison, the `network_details` property on Dispute is in private beta (secret feature) which is why it's not part of the public SDK for now. You likely have access to the beta on your Stripe account but others don't.
The property will be available in the SDK in the future once it is released publicly for everyone.
In the meantime you can use [this solution](https://github.com/stripe/stripe-java?tab=readme-ov-file#properties) to access extra properties in your code.

**Comment by zack-harrison** [comment]
I'm able to see this in my dashboard, but I don't get the data when I call the API. What am I doing wrong?

**Comment by remi-stripe** [comment]
It means you don't have access to the beta feature on that Stripe account. It's a private beta and access is limited. You can talk to our support team to ask if you can get access or be added to the wait list: https://support.stripe.com/contact
