### ISSUE TITLE
Add support for SATISPAY payment method

### ISSUE THREAD

**Issue by gabrielgatu** [stripe/stripe-java#1884]
### Is your feature request related to a problem? Please describe.

Satispay is an italian payment method, and Stripe is currently letting people access it through a beta program (we got in).

The only problem is that we're handling manually the list of payment methods accepted by our platform and Satispay is not yet supported by the Java library (updated to the latest 26.13.0-beta.1 version).

The problem is that Satispay is not yet listed between the accepted payment methods (SessionCreateParams.PaymentMethodType.SATISPAY doesn’t exists)

Could you please fix it?

**Comment by remi-stripe** [comment]
@gabrielgatu We don't add most betas to our beta SDKs today which is why Satispay is missing. We also don't really discuss most betas publicly. Please work directly with your Stripe point of contact that gave you access to the beta for further help. They can work internally with other people at Stripe to assess whether this is something we can do.
