### ISSUE TITLE
Putting Shipping Data on Charge Request

### ISSUE THREAD

**Issue by sthzg** [stripe/stripe-java#243]
According to the [stripe docs](https://stripe.com/docs/api/python#charge_object-shipping) one can put a `shipping` key on the `Charge` object. If I have a [`ShippingDetails`](https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/model/ShippingDetails.java) object populated, is there a convenience method to create the `Map` object that is necessary to put it on the charge params (or another workflow that is used in that case)?

Dummy code:

```java
ShippingDetails shippingDetails; // ...
chargeParams.put("shipping", shippingDetails.asMap());
```

Otherwise, do you think it would be worth a PR?

**Comment by brandur** [comment]
Good question!

For reference, [here's how the tests do it](https://github.com/stripe/stripe-java/blob/bf374048fbf4ef614bc775a06de27ecd8e4b37fb/src/test/java/com/stripe/StripeTest.java#L3360) (just the naive approach of manually building a map unfortunately).

The only doubt here I have is that generally it seems that this library reserves the typed model names for API responses and favors basic maps for parameter input. We should probably change this, but if we do, we'd probably want to use separate classes for parameters because the fields they contain will often not be symmetrical with the fields of the resources that they're used to create/update. Even if `ShippingDetails` looks very similar in the request/response for now, you could see a future there where fields are added to it that are not editable (e.g. imagine one for "delivery estimate").

That being the case, it might be better to wait a little until we can get some typed classes for input parameters in this library. Thoughts?

**Comment by sthzg** [comment]
Thanks for your reply, it sounds better than what I had in mind. I only thought about a verbose and unsophisticated version, much like handcrafting the fictional `asParamsMap()` method, possibly with an argument to specify the API target version `asParamsMap(String apiVersion)`. 

Thanks for pointing out the test class. I stumbled upon it yesterday while searching for the available API and as written in the README it is a good resource for examples.

**Comment by brandur** [comment]
@sthzg Cool! Okay, I'm going to close this down for the time being because we won't be taking immediate action, but let us know if you have any other thoughts or ideas here. Thanks!
