### ISSUE TITLE
Applying tax_percent in an invoice automatically generated for the update of a subscription

### ISSUE THREAD

**Issue by dgrmunch** [stripe/stripe-java#256]
When a subscription is updated (for example, from one kind of plan to another) the taxes are not applying in the generated invoice.
Taking for example these lines of code for a "Subscription" object "s":

        Map<String, Object> updateParams = new HashMap<String, Object>();
        updateParams.put("plan", getSelectedAccount().getCode());
        updateParams.put("prorate", "true");
        updateParams.put("tax_percent", "21");
        s.update(updateParams);

Stripe updates the plan correctly; however, the tax_percent is not applied in the generated invoice.

**Comment by remistr** [comment]
@dgrmunch: This code should not generate an invoice at all unless you move the customer between of different billing cycles as explained in our [Support article](https://support.stripe.com/questions/handling-subscription-changes). If you move the customer from a monthly plan to a monthly plan for example it simply creates pending invoice items that would then be picked up by the next invoice automatically.

If you create the invoice yourself via the API after that upgrade to charge the customer now for the price difference, then the invoice is created outside of the subscription itself. This means that id doesn't pick the `tax_percent` automatically in that case and you need to pass it yourself when you call the [Create Invoice API](https://stripe.com/docs/api#create_invoice)

**Comment by olivierbellone** [comment]
@dgrmunch This is by design. When you create an invoice, Stripe has no way to know whether the invoice is generated as part of a subscription or not, so by default it has no `tax_percent`.

If you wish to apply the subscription's `tax_percent` to this invoice, you will need to do so explicitly, by adding a [`tax_percent`](https://stripe.com/docs/api#create_invoice-tax_percent) parameter to your [invoice creation request](https://stripe.com/docs/api#create_invoice).

**Comment by dgrmunch** [comment]
@remistr Thanks for your response.

**Comment by dgrmunch** [comment]
@olivierbellone Great ;-) Thanks
