### ISSUE TITLE
Unable to load Stripe java library in spring project using Maven

### ISSUE THREAD

**Issue by gagansandhuz** [stripe/stripe-java#274]
Trying to implement Stripe as one of our payment gateway but when I tried to include it's library using maven getting below error.

`Offline / Missing artifact com.stripe:stripe-java:jar:1.45.0`

Have no clue why getting such an error..

**Comment by brandur** [comment]
Hey @gagansandhuz,

The Stripe package is [available from Maven's central repository](http://www.mkyong.com/maven/where-is-maven-central-repository/) which should be contacted by default. [Is it possible that you're trying to work offline?](https://stackoverflow.com/questions/7932109/maven-local-repository)

One tweak that you might want to try is using the latest version 1.46.0 as well, although it would be surprising if you had more success with that approach.

More generally though, is there anything here that suggests to you that this is a problem with the Stripe package? What happens when you try to bundle in other packages that you haven't downloaded before?
