### ISSUE TITLE
Request-ID at any time

### ISSUE THREAD

**Issue by javigs82** [stripe/stripe-java#287]
Hi @devs,
I'm starting to integrate stripe as part of our business process. We have defined a logging "in-house" system for tracking all request & responses. Request-Id is a mandatory data field to be recorded in order to have access to all stripe's server logs by request Id.

Could you please let me know how we can get the request-Id value of each request as stripe's documentation shown?

https://stripe.com/docs/api?lang=java#request_ids

Thanks in advance,
Javier.

**Comment by olivierbellone** [comment]
Hey @javigs82, sorry for the delay in replying.

Currently, the request ID is only surfaced for failed requests. When a request fails (i.e. when the API replies with a non-2xx status code), a `StripeException` is raised. You can retrieve the request ID for the failed request via the [`getRequestId()`](https://github.com/stripe/stripe-java/blob/075c4614f8342d73c3f03c18e5db87d6dad820c7/src/main/java/com/stripe/exception/StripeException.java#L22-L24) accessor.

At this time, the bindings don't surface the request ID for successful requests, since that's not terribly useful for most users. I unfortunately don't think it's going to be easy to add this feature without introducing breaking changes.

If this is something you absolutely need, you can always fork the Java bindings to add this feature yourself. For reference, [this](https://github.com/stripe/stripe-java/blob/c7d26216b09a5a5b288ef5550c59979209979bc5/src/main/java/com/stripe/net/LiveStripeResponseGetter.java#L435-L448) is the part you'd have to hack to return the request ID somehow.

**Comment by javigs82** [comment]
Hi Oliver, thanks for your answer.
I will fork this project and return the request-ID on the LiveResponseStripe.class.

In my opinion requestId is a mandatory data to build a solid audit trail over payments operations in PSPs.

Regards,
Javier.
