### ISSUE TITLE
Mark entities serializable/parselable to/from JSON with @SerializedName

### ISSUE THREAD

**Issue by artem-zinnatullin** [stripe/stripe-java#288]
Without explicit annotations json parsing stops working after obfuscation (we use Stripe Android SDK and ProGuard the app).

**Comment by olivierbellone** [comment]
Hey @artem-zinnatullin, sorry for the delay! In stripe-android's README, we mention that you need to exclude the `com.stripe` namespace from ProGuard: https://github.com/stripe/stripe-android#proguard

    -keep class com.stripe.** { *; }

That said, we will consider your suggestion. Thanks for sharing!

**Comment by artem-zinnatullin** [comment]
Hi @olivierbellone, right, stripe-android suggests ProGuard rule, but that rule excludes all Stripe's code from ProGuard which make it useless because we can not shrink unused classes from your sdk.

**Comment by brandur** [comment]
> Hi @olivierbellone, right, stripe-android suggests ProGuard rule, but that rule excludes all Stripe's code from ProGuard which make it useless because we can not shrink unused classes from your sdk.

Is it possible to have ProGuard exclude Stripe classes from _obfuscation only_? It seems like that's the step that's causing the problem here.

And also, is it an issue practically speaking that Stripe's code doesn't get shrunk? It may be an issue if you can't shrink any package, but I wouldn't think that the Stripe package would introduce an unmanageable amount of overhead itself.

More generally, I'd love to get to `@SerializedName` (explicitness is good), but because we don't really have any automated way of doing so, it's going to be quite a capital expenditure to move everything to do, and a little risky too because the tests don't check every field.

**Comment by ob-stripe** [comment]
As of stripe-java 8.0.0, all fields have an explicit `@SerializedName` annotation.
