### ISSUE TITLE
Accessing data in WebHooks

### ISSUE THREAD

**Issue by wildunne** [stripe/stripe-java#297]
I was just wondering how you take the validated Event object and turn it into an object of the appropriate type?

For example take an Event object which is a `invoice.payment_failed` and retrieve the Invoice that should be contained within.

**Comment by brandur** [comment]
Hi @wildunne,

Thanks to some crazy reflection magic assistance from GSON, the embedded `object` field within an event should be castable to the model associated with the event. Here's a modified example from the test suite where we pull an email out of a casted `Account`:

``` java
	@Test
	public void deserializeEventDataAccountEvent() throws IOException {
		String json = resource("account_event.json");
		Event e = StripeObject.PRETTY_PRINT_GSON.fromJson(json, Event.class);

		assertEquals(e.getType(), "account.updated");

		String accountEmail = ((com.stripe.model.Account)e.getData().getObject()).getEmail();
		System.out.println("Nested account email is: " + accountEmail);
	}
```

I'm going to add an additional test case in here so that at least there'll be one existing code example of this operation in the wild.

**Comment by brandur** [comment]
Added a basic test in #298.

I'm going to close this one out for now! Let us know if you have anymore questions about it.

**Comment by wildunne** [comment]
Nice, I assumed this was the case but didn't get the opportunity to test it yet.

Thanks for adding the demos!
