### ISSUE TITLE
Release notes with git commit subjects in them

### ISSUE THREAD

**Issue by leothekim** [stripe/stripe-java#313]
I find it helpful to have a list of git commits when tagging a release in Github, e.g.

```
$ git fetch origin master
$ git log --format='- %h "%s" (%ae)' $(last_release_tag)..
```

What do y'all think of adding the subject lines & short sha1s & authors from all commits since the previous release? It's nice to see a summary of what has changed, and the release emails are virtually bare.

**Comment by brandur** [comment]
Hi @leothekim,

Have you seen our CHANGELOG?
https://github.com/stripe/stripe-java/blob/master/CHANGELOG

This is probably going to be better than looking at commits in the majority of cases because our commit hygiene isn't amazing and it won't contain noise like merge commits.

If you're really looking for the commits though, it's pretty trivial to look at these with Git:

```
git log v2.8.0..v2.9.0
```

Or with GitHub:
https://github.com/stripe/stripe-java/compare/v2.8.0...v2.9.0

I'm not sure if I'm misunderstanding your question, but it seems to be that this information is already duplicated in enough places that adding it in one more isn't really necessary.

**Comment by leothekim** [comment]
Thanks, @brandur. The `git log` suggestion gives you info that can be gotten elsewhere, but it would have been a start. We do it internally because it saves other devs a little time from digging it up themselves, and it's not uncommon for other projects to have some background in their release emails, e.g. https://github.com/pantsbuild/intellij-pants-plugin/releases or https://github.com/mongodb/morphia/releases or https://github.com/twitter/finagle/releases or https://github.com/stripe/jquery.payment/releases.

If CHANGELOG and interpreting semver is how to know when upgrading is appropriate then I can run with that.

**Comment by brandur** [comment]
Hi @leothekim,

For the time being I'm going to take a relatively cheap solution to this by just including a link to the CHANGELOG within the release's body. It'll look something like this:

> Please see the CHANGELOG for details:
>
> https://github.com/stripe/stripe-java/blob/master/CHANGELOG

Agreed that detailed notes as seen in the other projects that you link above would be better, but I'll save that for a more comprehensive refactoring phase. Currently the Java bindings are the only language that we cut a GitHub release for anyway, so all of this stuff needs a closer look soon anyway.
