### ISSUE TITLE
Stripe no longer supports API requests made with TLS 1.0

### ISSUE THREAD

**Issue by vtherli** [stripe/stripe-java#333]
Stripe no longer supports API requests made with TLS 1.0. Please initiate HTTPS connections with TLS 1.2 or later. You can learn more about this at https://stripe.com/blog/upgrading-tls.

Gets the above error when I try to charge the card in test environment in Google App Engine (Java 7)

**Comment by ob-stripe** [comment]
Hi @vtherli. TLS 1.2 is not enabled by default in Java 7. You should upgrade to Java 8 if possible, otherwise you might be able to enable it by adding this flag to your Java command line: `-Ddeployment.security.TLSv1.2=true` (cf. [this StackOverflow answer](http://stackoverflow.com/a/36119342/5307473)).

As this is a problem with your own backend server and not with the library itself, I'm going to close this issue. If you have further questions or trouble, please reach out to support directly at https://support.stripe.com/email.

**Comment by jvanhees** [comment]
I'm having the same issue. I've enabled TLSv1.2 and when I check the supported SSL protocols (SSLContext.getDefault().getSupportedSSLParameters().getProtocols()), I'm getting the following array: [SSLv2Hello, SSLv3, TLSv1, TLSv1.1, TLSv1.2].

When I log the http request, It appears that the request is made with TLS1: *** ServerHello, TLSv1 . It seems to me that the error lies within the Stripe java package. I'm using version 4.7.0.

**Comment by ob-stripe** [comment]
@jvanhees This is likely something specific to your environment. I see that you've written to support separately -- someone will reply to you there.
