### ISSUE TITLE
Update examples?

### ISSUE THREAD

**Issue by chrylis** [stripe/stripe-java#354]
The new API appears to support JavaBeans-style configuration, but the examples still show the old JS-style map-based interface. It would be helpful, especially on the main README, to demonstrate the type-safe approach.

**Comment by ob-stripe** [comment]
Hi @chrylis. While Stripe objects do have accessors for each attribute, those accessors are only used to retrieve values from objects that are returned _from_ the API.

In order to pass parameters when sending requests _to_ the API, it is still necessary to use maps.

I'm going to close the issue, but please feel free to reply if you have more questions. You can also reach out to Stripe's support directly at https://support.stripe.com/email.
