### ISSUE TITLE
Received unknown parameter: currency; request-id: req_AvOLrDeRTNVyva

### ISSUE THREAD

**Issue by Nuwan-91** [stripe/stripe-java#388]
There is an issue when trying to interrogate  Stripe  using it's "Java API"

When trying to get the value for "currency", for which I have already set a value(I am going to create a new customer account) there is an error popping up saying that # **"**Received unknown parameter: currency; request-id: req_AvOLrDeRTNVyva**"**

The exact same error message is popping up not only for currency, but also for "**object**", "**created**", "**delinquent**", "**discount**" and "**livemode**" too.

![screenshot from 2017-06-28 09-43-10](https://user-images.githubusercontent.com/18524221/27620633-6e6bbe8a-5be8-11e7-9def-ee344071ed85.png)

For Example - **Received unknown parameter: object; request-id: req_AvOLrDeRTNVyva**
                        **Received unknown parameter: created; request-id: req_AvOLrDeRTNVyva**
                                                                                                                                         Like that,
                        Please try to resolve and thanks in advance.

**Comment by ob-stripe** [comment]
Hey @Nuwan-91. I have checked the three request IDs you mentioned. All three requests were [customer creation requests](https://stripe.com/docs/api#create_customer).

None of the parameters you mentioned (`currency`, `object`, `created`, `delinquent`,  `discount` or `livemode`) are valid parameters when creating a customer, so the API rejecting these parameters is the expected behavior.

As this is not an issue with the Java library, I'm going to close this issue. I recommend that you write to support using the form at https://support.stripe.com/email and explain exactly what you're trying to do.
