### ISSUE TITLE
Idempotent Requests

### ISSUE THREAD

**Issue by iLavryk** [stripe/stripe-java#389]
Hello, 
I faced an issue when i do charge request to the customer. 
I generate and put an idempotent key and make a charge so first time it works fine.
Just for example, Due to network problem i received ApiConnectionException and i do not know if the charge was really passed on stripe side. Then i try to make a charge again. And will receive another exception which says: "Requests should have unique idempotent key". Thats ok for now.
Then i need to somehow retrieve details about this charge. Due to i do not know status of it.
There is an option in API where I can put some metadata to my charge. Then i can retreive last charges from Stripe and find it by scaning my custom metadata.
But since i put metada to charge params each request became successful. It is just ignored my idempotent key. If i will not put metadata again, it works properly - throw an exception (because of the same idempotent key)

Here is the simplifyed code:

```
void doCharge(String customerId, String sourceId, String idemKey, boolean includeMetadata) throws Exception {
	HashMap<String, Object> chargeParams = new HashMap<>();
	chargeParams.put("amount", 1212);
	chargeParams.put("currency", "USD");
	chargeParams.put("description", "order id: 1, made by user: 2");
	chargeParams.put("customer", customerId);
	if (sourceId != null) {
		chargeParams.put("source", sourceId);
	}
	if (includeMetadata) {
		Map<String, Object> metadata = new HashMap<>();
		metadata.put("order_id", 1L);
		metadata.put("idempotent_key", idemKey);
		chargeParams.put("metadata", metadata);
	}
	RequestOptions options = RequestOptions.builder().setIdempotencyKey(idemKey).build();
	Charge.create(chargeParams, options);
}
```

If you try to call this method with includeMetadata=true with the same idemKey - it will work each time, but as soon as you changed it to false - first charge will be successful and next ones will throw an exception.

**Comment by ob-stripe** [comment]
Hi @iLavryk. Idempotent requests require that you send the exact same parameters each time.

If you send two requests with the same idempotency key and the same parameters, then the second request will get the correct reply, i.e. the same reply that the first request would have gotten if there hadn't been network issues. So for example if you're creating a charge, and the request succeeded, you'd get the charge object in the response.

If you send two requests with the same idempotency key but different parameters (including different metadata keys), then the second request will fail with the error you mentioned. This is because the different parameters cause the request to be interpreted as a new request, but you're reusing an idempotency key for another, different request.

As this isn't a problem with the Java library, I'm going to close the issue. Please reach out to support at https://support.stripe.com/email if you have further questions.
