### ISSUE TITLE
Unable to get fee from Charge Object

### ISSUE THREAD

**Issue by mamagotope** [stripe/stripe-java#507]
Hi i'm having some troubles getting the stripe fee and the net values of a Charge from the java library.
Maybe is possible and i'm just not seeing it.

**Comment by remi-stripe** [comment]
@mamagotope The fee details do not live on the Charge object. They live on the associated Balance Transaction [object](https://stripe.com/docs/api#balance_transaction_object) under the `fee` and `fee_details` properties.

You would have to retrieve that separately or use the [Expand feature](https://stripe.com/docs/api#expanding_objects) to get both at once.

This is more of a support question since it's not specific to the Java library so if you have any follow-up questions, you can reach out to our support team here: https://support.stripe.com/email
