### ISSUE TITLE
ExchangeRate does not work?

### ISSUE THREAD

**Issue by hzhaoAtSalesForce** [stripe/stripe-java#520]
When I try:
```
  public void testExceangeRate() throws Exception {
    Stripe.apiKey = this.secretKey;
    ExchangeRate e = ExchangeRate.retrieve("usd");
    log.info("For USD: ");
    log.info(MAPPER.writeValueAsString(e.getRates()));
    e = ExchangeRate.retrieve("cad");
    log.info("For CAD: ");
    log.info(MAPPER.writeValueAsString(e.getRates()));
  }
```

I got:
```
com.stripe.exception.InvalidRequestException: Unrecognized request URL (GET: /v1/exchange_rates/usd). Please see https://stripe.com/docs or we can help at https://support.stripe.com/.; request-id: req_xxxxxxxxx
```

**Comment by brandur-stripe** [comment]
@hzhaoAtSalesForce Sorry about the trouble here — exchange rates are still a gated feature with limited access. Let me see if I can grab some current state on its release.

**Comment by brandur-stripe** [comment]
Okay, I'm sorry to say that this feature has arrived at a slight impasse due to a changing of team owernship. We still expect its release, but possibly not in the immediate future.

If you have a use case where this is particularly important, would you mind emailing support@stripe.com? We could potentially get you gated in for early access to this feature.

**Comment by hzhaoAtSalesForce** [comment]
Thank you very much for the reply, my PM is talking directly with support team to see what we can get.

**Comment by remi-stripe** [comment]
Closing as I think it's more an internal decision and not a library bug/issue.
