### ISSUE TITLE
I cannot seem to link customer and source using the test account 

### ISSUE THREAD

**Issue by junaidjp** [stripe/stripe-java#550]
1)  Generate Token               
 
2) Call the below Method 

 public Customer createCustomer(String username,String token)  {
              Stripe.apiKey =STRIPE_API_KEY;
		Map<String, Object> customerParams = new HashMap<String, Object>();
		customerParams.put("email", username);
		customerParams.put("description", "tok_"+username);
		
		Customer customer = null;
		try {
			customer = Customer.create(customerParams);
			linkTokenToCustomer(customer.getId(), token); 
}
.......

3) Link the Token to Customer 

public boolean linkTokenToCustomer(String customerId, String tokenId) {
	
		Stripe.apiKey = STRIPE_API_KEY;;
		Customer customer = null;
	 boolean successfulLink = true;
		try {
			customer = Customer.retrieve(customerId);
			Map<String, Object> updateParams = new HashMap<String, Object>();
			updateParams.put("source", tokenId);
			customer.getSources().create(updateParams);

I keep getting 

"Customer ############  does not have a linked source with ID ##############@#."

**Comment by remi-stripe** [comment]
@junaidjp I don't think the error comes from that line of code. It would likely come from creating a charge and passing the token id again instead of the new card id (card_XXXX).

I would recommend talking to our support team instead as they can look at the logs in your account and help you figure out what is wrong. you can contact them here: https://support.stripe.com/email
