### ISSUE TITLE
Slow response time from API

### ISSUE THREAD

**Issue by ChuGer** [stripe/stripe-java#570]
Hello, we've building integration with Stripe Connect using Java SDK and Stripe account in Test Mode. We intended to switch to live mode in future to process real payments, but at the moment we are facing quite slow request processing time from Stripe API (version 2018-05-21) - some request (e.g. create a charge) took longer than 2 seconds.

 **So my questions are following:** 

- Where can I found SLA/request processing times for Stripe API endpoints?
- Is it possible that Live mode would have greater performance than Test mode?

Also I've created Jmeter test suite: 30 threads/users invoke API (create a charge) 10 times https://stripe.com/docs/api#create_charge, results are: 95% request ended in less than 2 seconds, there is request with processing time > 2 seconds, median value is 1.24 seconds.

![stripe_capture_2](https://user-images.githubusercontent.com/347001/43767844-ad61182a-9a3e-11e8-8675-d343ac5f90d1.png)

![stripe_capture_3](https://user-images.githubusercontent.com/347001/43767841-a973d07c-9a3e-11e8-8f3a-85f9bc7c588e.png)

**Comment by gh-stripe** [comment]
Hi @ChuGer, we don't have a document referencing the average response times but the values you're seeing are normal for test mode charge creation. A lot of internal checks are run when a charge is created and they take a good share of the time you saw. Regarding live mode requests we try to have comparable times with test mode ones but for charge creation it likely will be a bit longer since you need to add the conversation with the customer's bank.

This is more of a support question since it's not specific to the Java library so if you have any follow-up questions, you can reach out to our support team here: https://support.stripe.com/email
