### ISSUE TITLE
how do you get the product id after creating the product?

### ISSUE THREAD

**Issue by arch9745** [stripe/stripe-java#590]
According to the docs, Product.create is supposed to return json response including the product id. How do you get that? The only listed return I see is Product which has no public access to the id.

**Comment by ob-stripe** [comment]
@arch9745 You can call `getId()` to retrieve the value of the `id` attribute. You can't see the accessor in the source code because we use Project Lombok to automatically generate accessors for attributes.

That said, GitHub issues are specifically for reporting bugs or sending feature requests for Stripe's Java client library. They are not a support channel. If you have further questions, please reach out to Stripe's support at https://support.stripe.com/email.
