### ISSUE TITLE
NPE when accessing destinationObject of Payout

### ISSUE THREAD

**Issue by Flo354** [stripe/stripe-java#619]
Hi,

I am getting a list of Payout with the method `Payout.list` but it ends up with an NPE

```java
RequestOptions requestOptions = STRIPE_LIVE_BUILDER = new RequestOptions.RequestOptionsBuilder()
            .setApiKey("API_KEY") // Here is a test key
            .setClientId("CLIENT_ID")
            .build();
PayoutCollection payouts = Payout.list(params, requestOptions);

payouts.getData().get(0).getDestinationObject().toString(); // => NPE when calling toString
```

Some details, I am using my test key to get test payouts (since I do not have live payouts).
BUT, my bank account is a live one. 

May be it's related?

**Comment by remi-stripe** [comment]
@Flo354 When you retrieve a Payout via the API the `destination` property is a string by default such as a bank account id `ba_1234`. This means that by default `getDestinationObject()` would return null and you should not call `toString()` on it if it's null.

You should change your code to check the returned value before calling `toString()`. You also should avoid calling `getDestinationObject()` if you have not explicitly tried to [expand](https://stripe.com/docs/api#expanding_objects) the `destination` property since that would always be null.

If you wanted to expand the `destination` automatically then your code should be

```
RequestOptions requestOptions = STRIPE_LIVE_BUILDER = new RequestOptions.RequestOptionsBuilder()
            .setApiKey("API_KEY") // Here is a test key
            .setClientId("CLIENT_ID")
            .build();

List<String> expandList = new LinkedList<String>();
expandList.add("data.destination");

// Add the expand list to your params
params.put("expand", expandList);

PayoutCollection payouts = Payout.list(params, requestOptions);

payouts.getData().get(0).getDestinationObject().toString(); // => NPE when calling toString
```

**Comment by Flo354** [comment]
It works, sorry for my misunderstanding

**Comment by remi-stripe** [comment]
No worries, I would have assumed that `null.toString()` would just return an empty string instead of an NPE!
