### ISSUE TITLE
Charge.getSource() is an ExternalAccount

### ISSUE THREAD

**Issue by Flo354** [stripe/stripe-java#658]
Hi there,

According to the documentation (https://stripe.com/docs/api/charges/object) it seems that the source object returned is the complete one. However, the type of the source field in the "Charge" object is "ExternalAccount".

Why?

**Comment by ob-stripe** [comment]
@Flo354 A charge's source may be of a few different types: a [card](https://stripe.com/docs/api/cards), a [bank account](https://stripe.com/docs/api/customer_bank_accounts) or a [source](https://stripe.com/docs/api/sources) (yes, the term "source" is overloaded 😕).

In Stripe's Java library, those different types are represented by the `ExternalAccount` superclass. It's a rather bad name, since "external account" in the context of the Stripe's API refers to payout destinations, not charge sources. It will be fixed in a future (major) version, where the two concepts will be represented by two different interfaces (e.g. `PaymentSource` vs. `ExternalAccount`).

**Comment by Flo354** [comment]
Thanks @ob-stripe for the clarification! I was hoping not have to do two requests, but seems I'll have to...

Thanks again,

**Comment by ob-stripe** [comment]
@Flo354 Can you clarify what you're trying to do exactly? There may be a way to limit the number of requests.

**Comment by Flo354** [comment]
@ob-stripe, I just want to get the cardholder name. (All my Sources are Card).

**Comment by ob-stripe** [comment]
If you know that your payment sources are all cards, then you can directly cast the `ExternalAccount` to a `Card`:

```java
// charge is a Charge instance
Card card = (Card)charge.getSource();
String name = card.getName();
// Do something with name
```

Or, if you want to add a layer of safety:
```java
// charge is a Charge instance
String sourceType = charge.getSource().getObject();
if ("card".equals(sourceType))
{
    Card card = (Card)charge.getSource();
    String name = card.getName();
    // Do something with name
} else {
    // Unexpected source type, log an error with the charge's ID for later inspection
}
```

Hope this helps! If you have more questions or need more guidance, feel free to reach out to Stripe's support at https://support.stripe.com/email.

**Comment by Flo354** [comment]
That was exactly what I wanted to do! Thanks @ob-stripe!
