### ISSUE TITLE
 event.getDataObjectDeserializer().getObject() doesn't find data

### ISSUE THREAD

**Issue by baao** [stripe/stripe-java#771]
When receiving a webhook (charge.succeeded), above mentioned method returns empty, while the deprecated `event.getData().getObject();` still holds data:

```java
        Event event = ApiResource.GSON.fromJson(charge, Event.class);

        StripeObject o = event.getData().getObject();
        Charge cc = (Charge) o;
        System.out.println(cc.getAmount()); // 5454
        System.out.println(cc.getId()); // ch_xxx

        System.out.println("cc2");
        StripeObject o2 = event.getDataObjectDeserializer().getObject().orElseThrow();

        // throws error above
        // java.util.NoSuchElementException: No value present

        Charge cc2 = (Charge) o2;
        System.out.println(cc2.getAmount());
        System.out.println(cc2.getId());
```

Version info

java 12, com.stripe:stripe-java:9.8.0 and 9.9.0

Is this an error that I'm doing or is there a bug?

**Comment by ob-stripe** [comment]
@baao It's likely the case that your account's default API version is different than the API version stripe-java is pinned to (2019-03-14 for stripe-java 9.*).

As of stripe-java v8, the library is pinned to a specific API version. To avoid incorrectly deserializing objects (which could result in missing fields or even crashes), by default the library will not deserialize events that are formatted with a different API version than the one it expects.

Using `getData()` instead of `getDataObjectDeserializer()` is a fallback that you should only use when you know exactly what changed between the two API versions and are prepared to handle such changes. For more information:
- Migration guide for v8: https://github.com/stripe/stripe-java/wiki/Migration-guide-for-v8----version-upgrade#2-event-response-structure
- Migration guide for v9: https://github.com/stripe/stripe-java/wiki/Migration-guide-for-v9#event-deserialization

The recommended way to fix this is to upgrade your account's default API version to the latest (2019-03-14) so that incoming webhook events are formatted as the library expects and you can use `getDataObjectDeserializer()`.

Closing, but feel free to reply if you have any questions.

**Comment by baao** [comment]
Thanks @ob-stripe. Upgraded the API version and it's working as expected now.

**Comment by madven** [comment]
I am using stripe-java 19.45.0 version and my API version is 2020-03-02. i just installed Stripe CLI with homebrew. When I send `stripe trigger payment_intent.succeeded` from CLI, `event.getDataObjectDeserializer().getObject()` is returning `Optional.empty`. So I can't get `StripeObject`. Can you help me?

**Comment by madven** [comment]
> I am using stripe-java 19.45.0 version and my API version is 2020-03-02. I just installed Stripe CLI with homebrew. When I send `stripe trigger payment_intent.succeeded` from CLI, `event.getDataObjectDeserializer().getObject()` is returning `Optional.empty`. So I can't get `StripeObject`. Can you help me?

I tried with webhook. On the dashboard, I checked the "Webhook attempts" section. Inside the "Request to your endpoint", `data.object` is not empty. But on my side, `Event`'s `data.object` is `{}`. The problem could be related to the version mismatch.

**Comment by lieeew** [comment]
> [@baao](https://github.com/baao) It's likely the case that your account's default API version is different than the API version stripe-java is pinned to (2019-03-14 for stripe-java 9.*).
> 
> As of stripe-java v8, the library is pinned to a specific API version. To avoid incorrectly deserializing objects (which could result in missing fields or even crashes), by default the library will not deserialize events that are formatted with a different API version than the one it expects.
> 
> Using `getData()` instead of `getDataObjectDeserializer()` is a fallback that you should only use when you know exactly what changed between the two API versions and are prepared to handle such changes. For more information:
> 
>     * Migration guide for v8: https://github.com/stripe/stripe-java/wiki/Migration-guide-for-v8----version-upgrade#2-event-response-structure
> 
>     * Migration guide for v9: https://github.com/stripe/stripe-java/wiki/Migration-guide-for-v9#event-deserialization
> 
> 
> The recommended way to fix this is to upgrade your account's default API version to the latest (2019-03-14) so that incoming webhook events are formatted as the library expects and you can use `getDataObjectDeserializer()`.
> 
> Closing, but feel free to reply if you have any questions.

Thanks a lot for the clear explanation—really appreciate the help!
