### ISSUE TITLE
Expand Payment Method in Charge object

### ISSUE THREAD

**Issue by Thilakeswar** [stripe/stripe-java#836]
Team,

There isn't an option to expand the payment_method in the Charge Object. If it is available we will be able to hit single API to retrieve the PaymentMethod associated with Charge during below scenarios,
1) During Refunding a Charge
2) While retrieving a Charge

This is not an issue. But if available we will reduce multiple API hits.

**Comment by remi-stripe** [comment]
@Thilakeswar We do not support this in the API which is why you can't expand in the library. We strongly recommend not expanding or fetching the PaymentMethod since it could have changed since the Charge was created (for example if you updated the address).

Instead, we recommend reading from `payment_method_details` on the Charge. This is documented here: https://stripe.com/docs/payments/payment-intents/migration/reading-from-charges

**Comment by Thilakeswar** [comment]
@remi-stripe  Will we be able to use the same for Stripe ACH Debit and iDEAL payments too?
