### ISSUE TITLE
Invalid array response from Subscription API

### ISSUE THREAD

**Issue by rsalrsal** [stripe/stripe-java#885]
### The body attached to the create a new subscription for a current user looks as follows:

customer=cus_G7pfz7AEahIpv2&items=plan=plan_G6JGx1M7y3ia7C&source=tok_1Fba03FNCsdekPlKexTtEjvt

#### However, the response is "Invalid array" but I can't seem to understand where the issue is stemming. Any help with this would be greatly appreciated. Thanks!

**Comment by ob-stripe** [comment]
@rsalrsal Are you using the stripe-java client library? If so, can you provide the actual Java code you're using to send the subscription creation request?

**Comment by rsalrsal** [comment]
@ob-stripe Apologies, I might have posted my issue in the wrong repository. I'm currently creating a custom JS stripe integration to process subscriptions within our Wix site. Here's the backend code associated with the subscription API call. 

```
export async function subscription(token, item) {
	const cart = item;
	const apiKey = "sk_test_....";
	const response = await fetch("https://api.stripe.com/v1/subscriptions", {
		method: 'post',
		headers: {
			"Content-Type": "application/x-www-form-urlencoded",
			"Authorization": "Bearer " + apiKey
		},
		body: encodeBody(token, cart)
	});
	if (response.status >= 200 && response.status < 300) {
		// transaction successful - get charge ID
		const ret = await response.json();
		return { "chargeId": ret.id };
	}

	// transaction failed - return error messages and codes
	let res = await response.json();
	let err = res.error.message;
	let code = res.error.code;
	let type = res.error.type;
	return { "error": err, "code": code, "type": type };
} 
```

```
function encodeBody(token, cart) {
	let encoded = "";
	encoded = encoded.concat(createQueryString(cart));
	encoded = encoded.concat("&source=", encodeURI(token).replace("%3D", "="));
	console.log(encoded);
	return encoded;
}

const createQueryString = (data) => {
  return Object.keys(data).map(key => {
    let val = data[key]
    if (typeof val === 'object') val = createQueryString(val)
    return `${key}=${encodeURIComponent(`${val}`.replace(/\s/g, '_'))}`
  }).join('&')
}
```
I believe the issues simply stems from the string in query form from the first comment but I can;t figure out why from teh documentation.

Thanks again for your help and the quick response and feel free to let me know if I should post my issue somewhere else.

**Comment by remi-stripe** [comment]
@rsalrsal There are multiple issues here. The first one is that you seem to be doing this client-side which is forbidden. This call uses your Secret API key that should only be stored on your server. You need to make sure that you're never making this call client-side.

Then, you are making your own raw request and I would recommend that you use one of our official server-side libraries server-side instead: https://stripe.com/docs/libraries

Finally, here you seem to be passing invalid data because `items` should be an array and you're sending `items=plan=plan_123` which is invalid as a get parameter. It should be `items[plan]=plan_123` with properly url encoding.

I'm going to close this issue as github issues should be limited to bugs with the library. If you have follow-up questions, you should reach out to our support team https://support.stripe.com/contact
