### ISSUE TITLE
[Feature Request] Add discountable flag to Plan

### ISSUE THREAD

**Issue by stuartclayton** [stripe/stripe-java#916]
This would allow us to have a subscription with a mix of discounted and non-discounted plans.

**Comment by remi-stripe** [comment]
@stuartclayton Thanks for reaching out. This is definitely something we're thinking of. We're considering adding line item discounts at the moment which would let you apply to coupon to specific line items, or subscription items. No firm plans yet but it's definitely top of mind.

I'm going to close the github issue because we limit those to bugs in the library. Don't hesitate to reach out to our support team to provide that feedback: https://support.stripe.com/contact

**Comment by stuartclayton** [comment]
Thanks for your consideration, I realise it's a bit cheeky adding this here for developer visibility.  I think a discount on a subscription item would also get us what we need albeit in a much tricker fashion than utilising a discount that lives on a Customer or Subscription. (we would need to track the coupon ourselves and ensure it's added back to the subscription items whenever a Customer upgrades/downgrades etc) in the context of our SAAS app.
