### ISSUE TITLE
Issuing Balance no part of `com.stripe.model.Balance` object

### ISSUE THREAD

**Issue by jessym** [stripe/stripe-java#917]
**Java SDK Version**
16.2.0

**API Version**
2019-12-03

Executing the following code snippet shows that the Issuing Balance is not part of the `com.stripe.model.Balance` object.

```
Balance balance = Balance.retrieve();
JsonObject raw = balance.getRawJsonObject();
System.out.println("BALANCE");
System.out.println(balance.toJson());
System.out.println("RAW");
System.out.println(new GsonBuilder().setPrettyPrinting().create().toJson(raw));
```
This will log
```
BALANCE
{
  "object": "balance",
  "livemode": false,
  "available": [...],
  "pending": [...],
  "connect_reserved": null
}
```
followed by
```
RAW
{
  "object": "balance",
  "livemode": false,
  "available": [...],
  "pending": [...],
  "issuing": {
    "available": [...],
    "pending": [...]
  }
}
```
Which makes sense, since a CMD-F search for "issuing" gives no results here: https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/model/Balance.java

**Comment by remi-stripe** [comment]
Hey @jessym, thanks for reaching out! At the moment, the balance handling for Issuing is in private beta so not directly supported in stripe-java unfortunately. The reason is that we're working on a rework of the Balance system and hope to improve it next year.

What you should do for now is access those values via `getRawJsonObject()` as you found instead!

**Comment by remi-stripe** [comment]
Going to close this out as we added the Issuing balance in 19.8.0 https://github.com/stripe/stripe-java/blob/master/CHANGELOG.md#1980---2020-05-01
