### ISSUE TITLE
Fix  Invoice.list expansion parameter inconsistency

### ISSUE THREAD

**Issue by rabzu** [stripe/stripe-java#923]
Stripe java client `Invoice.list`  requires during expansion  `data` prefix when trying to get objects such as `data.charge` or `data.payment_intent`. This is inconsistent with object expansion with `invoice.retrieve` that does not require  `data` prefix in the expansion parameters and can be expanded with just `charge` and `payment_intent`.

**Comment by remi-stripe** [comment]
@rabzu This isn't a bug in the library or in the API, it's expected behaviour. When you retrieve an Invoice (or any object) you get the object directly and the field to expand is top-level. So you expand `charge` on an `Invoice`.

When you list Invoices, the object you get back is not an `Invoice`. It's a `List`. And the field `data` on the list is an array of `Invoice` objects. So if you want the `charge` property to be expanded, you have to mention that this is inside the `data` hash so `data.charge`.
