### ISSUE TITLE
List all invoices by status OPEN returns also COLLECTIBLE and filter by status COLLECTIBLE returns nothing

### ISSUE THREAD

**Issue by ltorbay** [stripe/stripe-java#958]
When you list all invoices and filter by status using the [list all invoices endpoint](https://stripe.com/docs/api/invoices/list), the OPEN status filter returns also the COLLECTIBLE invoices, and if the COLLECTIBLE filter status is used, no invoice is returned even if collectible invoices are present.

The other statuses seem to work as expected. 

Example code used: 
```
InvoiceCollection paid = Invoice.list(InvoiceListParams.builder()
                                 .setStatus(InvoiceListParams.Status.PAID)
                                 .setLimit(20L)
                                 .build()); // Returns PAID invoices as well as UNCOLLECTIBLE ones
InvoiceCollection uncollectible = Invoice.list(InvoiceListParams.builder()
                                 .setStatus(InvoiceListParams.Status.UNCOLLECTIBLE)
                                 .setLimit(20L)
                                 .build()); // Returns nothing
```

**Comment by remi-stripe** [comment]
@ltorbay I just tried this code on my end but I can't reproduce your issue. The second call only returns 2 invoices in my account which are the ones that are uncollectible and the first one does not return uncollectible invoice.

Are you sure this code is what you are running at the moment? Which version of stripe-java are you using? Would you be able to provide me with an example invoice id that is uncollectible so that I can confirm your code is sending the right parameter(s)?

**Comment by ltorbay** [comment]
@remi-stripe I am running Java 11 and Stripe 17.3.0 with Spring Boot 2.2.2.RELEASE

If i intercept the request run in the LiveStripeResponseGetter, i get the following parameters : 
url: "https://api.stripe.com/v1/invoices"
params:  size = 2
 "limit" -> 10
 "status" -> "open"
clazz: "class com.stripe.model.InvoiceCollection"

I don't have true 'test' invoices, most of them are generated using data from our running so i cannot give you a full example, but here goes a truncated one : 

```
{
  "object": "list",
  "data": [
    {
      "id": "****",
      "object": "invoice",
      "account_country": "US",
      "account_name": "****",
      "amount_due": 200000,
      "amount_paid": 0,
      "amount_remaining": 200000,
      "paid": false,
      "status": "open",
      "status_transitions": {
        "finalized_at": 1574694582,
        "marked_uncollectible_at": null,
        "paid_at": null,
        "voided_at": null
      }
    },
    {
      "id": "****",
      "object": "invoice",
      "account_country": "US",
      "account_name": "****",
      "amount_due": 200000,
      "amount_paid": 0,
      "amount_remaining": 200000,
      "status": "uncollectible",
      "status_transitions": {
        "finalized_at": 1574679568,
        "marked_uncollectible_at": null,
        "paid_at": null,
        "voided_at": null
      }
    }, 
    {...}
  ],
  "has_more": true,
  "url": "/v1/invoices"
}
```
I just noticed that my Uncollectible invoices have a null status_transitions.marked_uncollectible_at field. Could that be it ?

**Comment by remi-stripe** [comment]
@ltorbay Thanks for the extra details. It does look like this is a problem with some invoices in your account and not really with the library itself. Unfortunately I can't investigate further from here without looking at your account directly.

Can you reach out to our support team instead and provide them with example invoices (in_123) so that they can investigate this further? You can contact them here https://support.stripe.com/contact
