### ISSUE TITLE
PaymentMethod saved to Customer with save_payment_method=false

### ISSUE THREAD

**Issue by juerggnos** [stripe/stripe-java#987]
**Java SDK version**
18.3.0

**API version**
2020-03-02

**Java version**
OpenJDK 13.0.1

Creating a PaymentIntent with PaymentMethod and Customer leads to saving the PaymentMethod to the Customer even if `save_payment_method=false` (which is also the default).

According to the docs https://stripe.com/docs/api/payment_intents/create#create_payment_intent-save_payment_method this is wrong.

Example code:

```
PaymentIntentCreateParams paymentIntentCreateParams = PaymentIntentCreateParams.builder() //
                .setSavePaymentMethod(false) // should not be necessary as default is false according to the docs
                .setPaymentMethod(paymentMethodId) //
                .setCustomer(customerId) //
                .setConfirm(true) //
                .setCurrencycurrency) //
                .setAmount(amount) //
                .setApplicationFeeAmount(applicationFeeAmount) //
                .setConfirmationMethod(MANUAL) //
                .setTransferData(transferData) //
                .setSetupFutureUsage(ON_SESSION) //
                .build();
PaymentIntent.create(paymentIntentCreateParams);

```
This worked as expected with SDK version 10.4.0 and API version 2019-05-16

**Comment by remi-stripe** [comment]
@juerggnos Thanks for reaching out! The documentation for this parameter is a bit unclear right now as we've made other changes to the API recently. What `save_payment_method` does is control whether to attach the PaymentMethod _immediately_ to the Customer. This means you can do that even without confirming, or even if confirming fails.

What we've changed on our end is that if you set `setup_future_usage`, you're explicitly indicating that you are going to re-use that PaymentMethod in the future. So what we are doing, is that if the PaymentIntent is confirmed successfully, we then attach the PaymentMethod automatically for you. This removes the need to make an extra call after the fact in your webhook handler. 

This a recent change to the API that we made after hearing repeated feedback that this is what most integrations needed. The idea was to not attach PaymentMethods until the payment succeeded at which point, if `setup_future_usage` was set, the PaymentMethod would be automatically attached and re-usable for future payments.

If you don't want the automatic attachment in that case because you don't plan to re-use the card you should make sure that you don't send `setup_future_usage` in your call.

I hope this clarifies the confusion and I flagged internally that we should update the docstring.

**Comment by juerggnos** [comment]
Okay, thanks for this clarification.
